name: Mover issue para In Progress ao criar branch

on:
  push:
    branches: [ master, issue-* ] # Ação será acionada quando fizer push para qualquer branch que comece com "issue-"

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mover issue para In Progress
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const core = require('@actions/core');
            const github = require('@actions/github');
            
            // Extrair o número da issue do nome da branch
            const branchName = github.context.ref.replace('refs/heads/', ''); // Remover prefixo "refs/heads/"
            const issueNumberMatch = branchName.match(/^issue-(\d+)$/);
            
            if (!issueNumberMatch) {
              throw new Error('Nome da branch não segue o padrão "issue-<numero-da-issue>"');
            }

            const issueNumber = issueNumberMatch[1];

            // Atualizar a issue para o status "In Progress" ou o que desejar
            const response = await github.rest.issues.update({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: issueNumber,
              state: 'open' // Mantenha "open" para que a issue não seja fechada; "closed" para fechá-la
            });
            
            core.setOutput('issue_status', response.status);
