name: Mover issue para In Progress ao criar branch

on:
  push:
    branches: [ master ]

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mover issue para In Progress
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueUrl = 'https://github.com/rogerdgela/sablecard/issues/' + github.context.issue.number;
            const response = await github.rest.issues.update({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: github.context.issue.number,
              state: 'open' // ou 'closed' conforme a necessidade
            });
            core.setOutput('issue_status', response.status);
