name: Move Issue to Done on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  move-issue-to-done:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to Done
        run: |
          ISSUE_NUMBER=$(echo "$GITHUB_REF" | sed 's/^refs\/pull\/\([0-9]*\)\/.*$/\1/')
          gh project card move --column "Done" --issue ${ISSUE_NUMBER}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
