name: Move Issue to In Progress on Branch Creation

on:
  create:
    branches:
      - 'issue-*'

jobs:
  move-issue-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress
        run: |
          ISSUE_NUMBER=${GITHUB_REF#refs/heads/issue-}
          gh project card move --column "In progress" --issue ${ISSUE_NUMBER}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
